/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.alejandro.first;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @BeforeAll static void initializeApp(){
        App test = new App();
    }
    @Test void convertingRight(){
        assertEquals(App.convert(2,"ft","m"), 0.6096);
    }
    /* @Test void failedTest(){
        assertEquals(App.convert(2,"ft","m"), 0.6196);
    }
     */
}
